// assignmentsData.js — mock data for Assignments page.
// Replace with real API calls when backend is ready.

export const ASSIGNMENTS = [
  {
    id: 'a1',
    title: 'Lab Report #4 — Memory Allocation',
    course: 'Software Engineering',
    courseCode: 'SE-301',
    instructor: 'Dr. Aris Thorne',
    instructorInitials: 'AT',
    dueDate: '2026-07-22T23:59:00',
    submittedDate: null,
    status: 'pending',
    priority: 'high',
    marks: null,
    totalMarks: 50,
    type: 'Lab Report',
    files: [],
    feedback: null,
    color: 'ac-blue',
  },
  {
    id: 'a2',
    title: 'Binary Trees — Implementation Exercise',
    course: 'Data Structures & Algorithms',
    courseCode: 'SE-102',
    instructor: 'Prof. Elena Rostova',
    instructorInitials: 'ER',
    dueDate: '2026-07-24T23:59:00',
    submittedDate: null,
    status: 'pending',
    priority: 'high',
    marks: null,
    totalMarks: 40,
    type: 'Programming',
    files: [],
    feedback: null,
    color: 'ac-purple',
  },
  {
    id: 'a3',
    title: 'Neural Network Training — Notebook Submission',
    course: 'Machine Learning',
    courseCode: 'DS-301',
    instructor: 'Dr. Marcus Vance',
    instructorInitials: 'MV',
    dueDate: '2026-07-28T23:59:00',
    submittedDate: null,
    status: 'pending',
    priority: 'medium',
    marks: null,
    totalMarks: 60,
    type: 'Project',
    files: [],
    feedback: null,
    color: 'ac-emerald',
  },
  {
    id: 'a4',
    title: 'Quiz 3 — Cryptographic Protocols',
    course: 'Cyber Security Principles',
    courseCode: 'CS-301',
    instructor: 'Prof. Sarah Jenkins',
    instructorInitials: 'SJ',
    dueDate: '2026-07-20T23:59:00',
    submittedDate: '2026-07-19T14:30:00',
    status: 'submitted',
    priority: 'medium',
    marks: null,
    totalMarks: 30,
    type: 'Quiz',
    files: ['quiz3_answers.pdf'],
    feedback: null,
    color: 'ac-amber',
  },
  {
    id: 'a5',
    title: 'Market Segmentation Analysis Report',
    course: 'Business Analytics',
    courseCode: 'DS-403',
    instructor: 'Prof. James Whitfield',
    instructorInitials: 'JW',
    dueDate: '2026-07-15T23:59:00',
    submittedDate: '2026-07-14T20:10:00',
    status: 'graded',
    priority: 'low',
    marks: 42,
    totalMarks: 50,
    type: 'Report',
    files: ['market_analysis.docx'],
    feedback: 'Excellent analysis. Well-structured arguments and strong use of data visualisation.',
    color: 'ac-rose',
  },
  {
    id: 'a6',
    title: 'OOP Design Patterns — Reflection Essay',
    course: 'Software Engineering',
    courseCode: 'SE-301',
    instructor: 'Dr. Aris Thorne',
    instructorInitials: 'AT',
    dueDate: '2026-07-10T23:59:00',
    submittedDate: '2026-07-09T11:00:00',
    status: 'graded',
    priority: 'medium',
    marks: 36,
    totalMarks: 40,
    type: 'Essay',
    files: ['oop_essay.pdf'],
    feedback: 'Good depth of understanding. Could improve on real-world examples.',
    color: 'ac-blue',
  },
  {
    id: 'a7',
    title: 'Sorting Algorithm Complexity — Written Analysis',
    course: 'Data Structures & Algorithms',
    courseCode: 'SE-102',
    instructor: 'Prof. Elena Rostova',
    instructorInitials: 'ER',
    dueDate: '2026-07-12T23:59:00',
    submittedDate: '2026-07-14T08:00:00',
    status: 'late',
    priority: 'high',
    marks: 28,
    totalMarks: 40,
    type: 'Written',
    files: ['sorting_analysis.pdf'],
    feedback: 'Submitted late. Marks deducted. Content was satisfactory.',
    color: 'ac-purple',
  },
  {
    id: 'a8',
    title: 'Penetration Testing Lab — Kali Linux Exercise',
    course: 'Cyber Security Principles',
    courseCode: 'CS-301',
    instructor: 'Prof. Sarah Jenkins',
    instructorInitials: 'SJ',
    dueDate: '2026-07-08T23:59:00',
    submittedDate: null,
    status: 'overdue',
    priority: 'high',
    marks: null,
    totalMarks: 50,
    type: 'Lab',
    files: [],
    feedback: null,
    color: 'ac-amber',
  },
];

export const COURSE_FILTER_OPTIONS = [
  'All Courses',
  'SE-301 · Software Engineering',
  'SE-102 · Data Structures & Algorithms',
  'DS-301 · Machine Learning',
  'CS-301 · Cyber Security Principles',
  'DS-403 · Business Analytics',
];

export const STATUS_FILTER_OPTIONS = ['All Status', 'pending', 'submitted', 'graded', 'late', 'overdue'];
export const PRIORITY_OPTIONS      = ['All Priority', 'high', 'medium', 'low'];
export const TYPE_OPTIONS          = ['All Types', 'Lab Report', 'Programming', 'Project', 'Quiz', 'Report', 'Essay', 'Written', 'Lab'];

export const SORT_OPTIONS = [
  { value: 'due-asc',      label: 'Due Date (Earliest)'  },
  { value: 'due-desc',     label: 'Due Date (Latest)'    },
  { value: 'title-asc',    label: 'Title A → Z'          },
  { value: 'priority-desc',label: 'Priority (High → Low)'},
  { value: 'marks-desc',   label: 'Marks (High → Low)'   },
];

export const TABS = [
  { key: 'all',       label: 'All'       },
  { key: 'pending',   label: 'Pending'   },
  { key: 'submitted', label: 'Submitted' },
  { key: 'graded',    label: 'Graded'    },
  { key: 'overdue',   label: 'Overdue'   },
];
