// coursesData.js — mock data for My Courses dashboard page.
// Swap for real API when backend is ready.

export const MY_COURSES = [
  {
    id: 'se301',
    code: 'SE-301',
    title: 'Software Engineering',
    instructor: 'Dr. Aris Thorne',
    instructorInitials: 'AT',
    semester: 'Fall 2026',
    credits: 3,
    category: 'Engineering',
    status: 'ongoing',
    progress: 62,
    nextClass: 'Today · 09:00 AM',
    assignments: { total: 8, pending: 2 },
    grade: 'A-',
    color: 'cc-blue',
    gradient: 'linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%)',
    abbr: 'SE',
  },
  {
    id: 'se102',
    code: 'SE-102',
    title: 'Data Structures & Algorithms',
    instructor: 'Prof. Elena Rostova',
    instructorInitials: 'ER',
    semester: 'Fall 2026',
    credits: 4,
    category: 'Computer Science',
    status: 'ongoing',
    progress: 48,
    nextClass: 'Tomorrow · 11:30 AM',
    assignments: { total: 10, pending: 3 },
    grade: 'B+',
    color: 'cc-purple',
    gradient: 'linear-gradient(135deg,#2e1065 0%,#7c3aed 100%)',
    abbr: 'DSA',
  },
  {
    id: 'ds301',
    code: 'DS-301',
    title: 'Machine Learning',
    instructor: 'Dr. Marcus Vance',
    instructorInitials: 'MV',
    semester: 'Fall 2026',
    credits: 3,
    category: 'Data Science',
    status: 'ongoing',
    progress: 35,
    nextClass: 'Wed · 02:00 PM',
    assignments: { total: 6, pending: 1 },
    grade: 'A',
    color: 'cc-emerald',
    gradient: 'linear-gradient(135deg,#064e3b 0%,#10b981 100%)',
    abbr: 'ML',
  },
  {
    id: 'cs301',
    code: 'CS-301',
    title: 'Cyber Security Principles',
    instructor: 'Prof. Sarah Jenkins',
    instructorInitials: 'SJ',
    semester: 'Fall 2026',
    credits: 3,
    category: 'Cyber Security',
    status: 'ongoing',
    progress: 71,
    nextClass: 'Thu · 04:30 PM',
    assignments: { total: 7, pending: 0 },
    grade: 'A',
    color: 'cc-amber',
    gradient: 'linear-gradient(135deg,#451a03 0%,#f59e0b 100%)',
    abbr: 'CS',
  },
  {
    id: 'ds403',
    code: 'DS-403',
    title: 'Business Analytics',
    instructor: 'Prof. James Whitfield',
    instructorInitials: 'JW',
    semester: 'Fall 2026',
    credits: 2,
    category: 'Business',
    status: 'ongoing',
    progress: 28,
    nextClass: 'Fri · 10:00 AM',
    assignments: { total: 5, pending: 2 },
    grade: 'B',
    color: 'cc-rose',
    gradient: 'linear-gradient(135deg,#4c0519 0%,#f43f5e 100%)',
    abbr: 'BA',
  },
  {
    id: 'se201',
    code: 'SE-201',
    title: 'Object-Oriented Design',
    instructor: 'Dr. Aris Thorne',
    instructorInitials: 'AT',
    semester: 'Spring 2026',
    credits: 3,
    category: 'Engineering',
    status: 'completed',
    progress: 100,
    nextClass: '—',
    assignments: { total: 9, pending: 0 },
    grade: 'A',
    color: 'cc-blue',
    gradient: 'linear-gradient(135deg,#1e3a5f 0%,#2563eb 100%)',
    abbr: 'OOD',
  },
  {
    id: 'ds202',
    code: 'DS-202',
    title: 'Exploratory Data Analysis',
    instructor: 'Prof. Elena Rostova',
    instructorInitials: 'ER',
    semester: 'Spring 2026',
    credits: 3,
    category: 'Data Science',
    status: 'completed',
    progress: 100,
    nextClass: '—',
    assignments: { total: 8, pending: 0 },
    grade: 'A-',
    color: 'cc-emerald',
    gradient: 'linear-gradient(135deg,#064e3b 0%,#10b981 100%)',
    abbr: 'EDA',
  },
  {
    id: 'cs401',
    code: 'CS-401',
    title: 'Digital Forensics',
    instructor: 'Dr. Marcus Vance',
    instructorInitials: 'MV',
    semester: 'Spring 2027',
    credits: 3,
    category: 'Cyber Security',
    status: 'upcoming',
    progress: 0,
    nextClass: 'Starts Jan 12',
    assignments: { total: 0, pending: 0 },
    grade: '—',
    color: 'cc-purple',
    gradient: 'linear-gradient(135deg,#2e1065 0%,#7c3aed 100%)',
    abbr: 'DF',
  },
];

export const SEMESTERS  = ['All', 'Fall 2026', 'Spring 2026', 'Spring 2027'];
export const CATEGORIES = ['All', 'Engineering', 'Computer Science', 'Data Science', 'Cyber Security', 'Business'];
export const STATUSES   = ['All', 'ongoing', 'completed', 'upcoming'];
export const SORT_OPTIONS = [
  { value: 'title-asc',     label: 'Title A → Z'       },
  { value: 'title-desc',    label: 'Title Z → A'       },
  { value: 'progress-desc', label: 'Progress High → Low'},
  { value: 'progress-asc',  label: 'Progress Low → High'},
  { value: 'credits-desc',  label: 'Credits High → Low' },
];
